apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: tracebus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: your-registry/tracebus-worker:0.1.0
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        livenessProbe:
          exec:
            command: ["sh","-c","pgrep worker"]
          initialDelaySeconds: 10
          periodSeconds: 10
